//layout basically visible on the whole application.like header and footer
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ //object destructuring
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-teal-800 p-4 flex gap-10">
        <Link href="/home">Home</Link>
        <Link href="/dashboard">Dashboard</Link>
        <Link href="/settings">Settings</Link>
        <Link href="/blog">Blog</Link>
        </header>
        
        {children}
        <footer className="bg-teal-950 p-5 ">This is footer
          
          </footer></body>
    </html>
  );
}
